# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Servor_Or_MIT_Widget = QtWidgets.QWidget(self.centralwidget)
        self.Servor_Or_MIT_Widget.setGeometry(QtCore.QRect(10, 20, 291, 101))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Servor_Or_MIT_Widget.setFont(font)
        self.Servor_Or_MIT_Widget.setObjectName("Servor_Or_MIT_Widget")
        self.Servor_Or_MIT_Combobox = QtWidgets.QFontComboBox(self.Servor_Or_MIT_Widget)
        self.Servor_Or_MIT_Combobox.setGeometry(QtCore.QRect(10, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Servor_Or_MIT_Combobox.setFont(font)
        self.Servor_Or_MIT_Combobox.setCurrentText("")
        self.Servor_Or_MIT_Combobox.setObjectName("Servor_Or_MIT_Combobox")
        self.Servor_Or_MIT_label = QtWidgets.QLabel(self.Servor_Or_MIT_Widget)
        self.Servor_Or_MIT_label.setGeometry(QtCore.QRect(10, 20, 251, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Servor_Or_MIT_label.setFont(font)
        self.Servor_Or_MIT_label.setObjectName("Servor_Or_MIT_label")
        self.ServorOrMITModeUpdateBtn = QtWidgets.QPushButton(self.Servor_Or_MIT_Widget)
        self.ServorOrMITModeUpdateBtn.setGeometry(QtCore.QRect(220, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ServorOrMITModeUpdateBtn.setFont(font)
        self.ServorOrMITModeUpdateBtn.setObjectName("ServorOrMITModeUpdateBtn")
        self.ModeWidget = QtWidgets.QWidget(self.centralwidget)
        self.ModeWidget.setGeometry(QtCore.QRect(10, 160, 291, 111))
        self.ModeWidget.setObjectName("ModeWidget")
        self.ModeLabel = QtWidgets.QLabel(self.ModeWidget)
        self.ModeLabel.setGeometry(QtCore.QRect(10, 10, 108, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ModeLabel.setFont(font)
        self.ModeLabel.setObjectName("ModeLabel")
        self.ModeCombobox = QtWidgets.QFontComboBox(self.ModeWidget)
        self.ModeCombobox.setGeometry(QtCore.QRect(10, 40, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ModeCombobox.setFont(font)
        self.ModeCombobox.setCurrentText("")
        self.ModeCombobox.setObjectName("ModeCombobox")
        self.ModeUpdateBtn = QtWidgets.QPushButton(self.ModeWidget)
        self.ModeUpdateBtn.setGeometry(QtCore.QRect(230, 40, 61, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ModeUpdateBtn.setFont(font)
        self.ModeUpdateBtn.setObjectName("ModeUpdateBtn")
        self.SevorParaWidget = QtWidgets.QWidget(self.centralwidget)
        self.SevorParaWidget.setGeometry(QtCore.QRect(330, 20, 441, 281))
        self.SevorParaWidget.setObjectName("SevorParaWidget")
        self.ServorLabel = QtWidgets.QLabel(self.SevorParaWidget)
        self.ServorLabel.setGeometry(QtCore.QRect(0, 0, 151, 24))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ServorLabel.setFont(font)
        self.ServorLabel.setObjectName("ServorLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.SevorParaWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 401, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CurrentLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentLabel.setFont(font)
        self.CurrentLabel.setObjectName("CurrentLabel")
        self.horizontalLayout.addWidget(self.CurrentLabel)
        self.CurrentLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CurrentLineEdit.setFont(font)
        self.CurrentLineEdit.setObjectName("CurrentLineEdit")
        self.horizontalLayout.addWidget(self.CurrentLineEdit)
        self.MaxCurLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MaxCurLabel.setFont(font)
        self.MaxCurLabel.setObjectName("MaxCurLabel")
        self.horizontalLayout.addWidget(self.MaxCurLabel)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.SevorParaWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(19, 79, 401, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.VelocityLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.VelocityLabel.setFont(font)
        self.VelocityLabel.setObjectName("VelocityLabel")
        self.horizontalLayout_2.addWidget(self.VelocityLabel)
        self.VelocityLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.VelocityLineEdit.setFont(font)
        self.VelocityLineEdit.setObjectName("VelocityLineEdit")
        self.horizontalLayout_2.addWidget(self.VelocityLineEdit)
        self.MaxVelLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MaxVelLabel.setFont(font)
        self.MaxVelLabel.setObjectName("MaxVelLabel")
        self.horizontalLayout_2.addWidget(self.MaxVelLabel)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.SevorParaWidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 130, 401, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PositionLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PositionLabel.setFont(font)
        self.PositionLabel.setObjectName("PositionLabel")
        self.horizontalLayout_3.addWidget(self.PositionLabel)
        self.PositionLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PositionLineEdit.setFont(font)
        self.PositionLineEdit.setObjectName("PositionLineEdit")
        self.horizontalLayout_3.addWidget(self.PositionLineEdit)
        self.MaxPosLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MaxPosLabel.setFont(font)
        self.MaxPosLabel.setObjectName("MaxPosLabel")
        self.horizontalLayout_3.addWidget(self.MaxPosLabel)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.SevorParaWidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(19, 180, 401, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.AccelLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.AccelLabel.setFont(font)
        self.AccelLabel.setObjectName("AccelLabel")
        self.horizontalLayout_4.addWidget(self.AccelLabel)
        self.AccelLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AccelLineEdit.setFont(font)
        self.AccelLineEdit.setObjectName("AccelLineEdit")
        self.horizontalLayout_4.addWidget(self.AccelLineEdit)
        self.MaxAccelLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MaxAccelLabel.setFont(font)
        self.MaxAccelLabel.setObjectName("MaxAccelLabel")
        self.horizontalLayout_4.addWidget(self.MaxAccelLabel)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.SevorParaWidget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(20, 230, 401, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.IDLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.IDLabel.setFont(font)
        self.IDLabel.setObjectName("IDLabel")
        self.horizontalLayout_8.addWidget(self.IDLabel)
        self.IDLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.IDLineEdit.setObjectName("IDLineEdit")
        self.horizontalLayout_8.addWidget(self.IDLineEdit)
        self.MITParaWidget = QtWidgets.QWidget(self.centralwidget)
        self.MITParaWidget.setGeometry(QtCore.QRect(330, 310, 441, 221))
        self.MITParaWidget.setObjectName("MITParaWidget")
        self.MIT_ParaLabel = QtWidgets.QLabel(self.MITParaWidget)
        self.MIT_ParaLabel.setGeometry(QtCore.QRect(10, 10, 171, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MIT_ParaLabel.setFont(font)
        self.MIT_ParaLabel.setObjectName("MIT_ParaLabel")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.MITParaWidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 50, 401, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.KpLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.KpLabel.setFont(font)
        self.KpLabel.setObjectName("KpLabel")
        self.horizontalLayout_5.addWidget(self.KpLabel)
        self.KpLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.KpLineEdit.setObjectName("KpLineEdit")
        self.horizontalLayout_5.addWidget(self.KpLineEdit)
        self.MaxKpLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.MaxKpLabel.setFont(font)
        self.MaxKpLabel.setObjectName("MaxKpLabel")
        self.horizontalLayout_5.addWidget(self.MaxKpLabel)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.MITParaWidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(20, 110, 401, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.KdLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.KdLabel.setFont(font)
        self.KdLabel.setObjectName("KdLabel")
        self.horizontalLayout_6.addWidget(self.KdLabel)
        self.KdLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.KdLineEdit.setObjectName("KdLineEdit")
        self.horizontalLayout_6.addWidget(self.KdLineEdit)
        self.MaxKdLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.MaxKdLabel.setFont(font)
        self.MaxKdLabel.setObjectName("MaxKdLabel")
        self.horizontalLayout_6.addWidget(self.MaxKdLabel)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.MITParaWidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(20, 170, 401, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.TorqueLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.TorqueLabel.setFont(font)
        self.TorqueLabel.setObjectName("TorqueLabel")
        self.horizontalLayout_7.addWidget(self.TorqueLabel)
        self.TorqueLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.TorqueLineEdit.setObjectName("TorqueLineEdit")
        self.horizontalLayout_7.addWidget(self.TorqueLineEdit)
        self.MaxTorqueLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.MaxTorqueLabel.setFont(font)
        self.MaxTorqueLabel.setObjectName("MaxTorqueLabel")
        self.horizontalLayout_7.addWidget(self.MaxTorqueLabel)
        self.CalculatorWidget = QtWidgets.QWidget(self.centralwidget)
        self.CalculatorWidget.setGeometry(QtCore.QRect(30, 520, 751, 80))
        self.CalculatorWidget.setObjectName("CalculatorWidget")
        self.CalculatePushButton = QtWidgets.QPushButton(self.CalculatorWidget)
        self.CalculatePushButton.setGeometry(QtCore.QRect(0, 10, 128, 32))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CalculatePushButton.setFont(font)
        self.CalculatePushButton.setObjectName("CalculatePushButton")
        self.CalculatorBrowser = QtWidgets.QTextBrowser(self.CalculatorWidget)
        self.CalculatorBrowser.setGeometry(QtCore.QRect(150, 20, 591, 51))
        self.CalculatorBrowser.setObjectName("CalculatorBrowser")
        self.SearchWidget = QtWidgets.QWidget(self.centralwidget)
        self.SearchWidget.setGeometry(QtCore.QRect(30, 620, 751, 221))
        self.SearchWidget.setObjectName("SearchWidget")
        self.SearchTextBrowser = QtWidgets.QTextBrowser(self.SearchWidget)
        self.SearchTextBrowser.setGeometry(QtCore.QRect(150, 50, 591, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SearchTextBrowser.setFont(font)
        self.SearchTextBrowser.setObjectName("SearchTextBrowser")
        self.SearchPushButton = QtWidgets.QPushButton(self.SearchWidget)
        self.SearchPushButton.setGeometry(QtCore.QRect(10, 0, 128, 32))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SearchPushButton.setFont(font)
        self.SearchPushButton.setObjectName("SearchPushButton")
        self.SearchLineEdit = QtWidgets.QLineEdit(self.SearchWidget)
        self.SearchLineEdit.setGeometry(QtCore.QRect(150, 0, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SearchLineEdit.setFont(font)
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 290, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.SetOriginTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.SetOriginTextBrowser.setGeometry(QtCore.QRect(20, 340, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SetOriginTextBrowser.setFont(font)
        self.SetOriginTextBrowser.setObjectName("SetOriginTextBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Servor_Or_MIT_label.setText(_translate("MainWindow", "伺服模式或MIT模式"))
        self.ServorOrMITModeUpdateBtn.setText(_translate("MainWindow", "Update"))
        self.ModeLabel.setText(_translate("MainWindow", "运行模式"))
        self.ModeUpdateBtn.setText(_translate("MainWindow", "Update"))
        self.ServorLabel.setText(_translate("MainWindow", "基本模式参数"))
        self.CurrentLabel.setText(_translate("MainWindow", "电流："))
        self.MaxCurLabel.setText(_translate("MainWindow", "<100"))
        self.VelocityLabel.setText(_translate("MainWindow", "速度："))
        self.MaxVelLabel.setText(_translate("MainWindow", "<100"))
        self.PositionLabel.setText(_translate("MainWindow", "位置："))
        self.MaxPosLabel.setText(_translate("MainWindow", "<100"))
        self.AccelLabel.setText(_translate("MainWindow", "加速度："))
        self.MaxAccelLabel.setText(_translate("MainWindow", "<10"))
        self.IDLabel.setText(_translate("MainWindow", "ID:"))
        self.MIT_ParaLabel.setText(_translate("MainWindow", "MIT模式额外参数"))
        self.KpLabel.setText(_translate("MainWindow", "Kp:"))
        self.MaxKpLabel.setText(_translate("MainWindow", "<500"))
        self.KdLabel.setText(_translate("MainWindow", "Kd:"))
        self.MaxKdLabel.setText(_translate("MainWindow", "<50"))
        self.TorqueLabel.setText(_translate("MainWindow", "扭矩:"))
        self.MaxTorqueLabel.setText(_translate("MainWindow", "<144"))
        self.CalculatePushButton.setText(_translate("MainWindow", "计算指令"))
        self.CalculatorBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p></body></html>"))
        self.SearchPushButton.setText(_translate("MainWindow", "查询指令"))
        self.label.setText(_translate("MainWindow", "原点设置："))
